services:
  app:
    image: my-php-apache      # Custom PHP & Apache image

    
    volumes:
      - .:/var/www/html       # Mount current folder
    depends_on:
      - db
    working_dir: /var/www/html
    command: apache2-foreground

  db:
    image: mysql:8


    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
